### ISSUE TITLE
About visualizing feature maps

### ISSUE THREAD

**Issue by midsdsy** [Megvii-BaseDetection/BorderDet#24]
Thanks for contributing this project.
I'm studying this work and try to understand some details in feature enhancing. And recently i'm confused about where the chosen extreme point in feature maps actually. Does it choose the true extreme point as we think? I want to visualize my prediction result and the extreme point just as the Fig.4 in paper. And i haven't found relevant code in project.  Could you please share the relevant code if it's ok?
Looking forward to your reply.

**Comment by Maycbj** [comment]
Since this repo torch-based implementation, I believe it is easy to get the heatmap of the extreme point, and then you can use opencv to get the visual results.
Here are the visualization of the extreme point.
[borderdet_border_feature_for_dense_object_detection-Supplementary Material.pdf](https://github.com/Megvii-BaseDetection/BorderDet/files/5406491/borderdet_border_feature_for_dense_object_detection-Supplementary.Material.pdf)

**Comment by midsdsy** [comment]
Thanks
